export const CUSTOM_EVENTS = Object.freeze({
    ENEMY_INIT: 'ENEMY_INIT',
    ENEMY_DESTROYED: 'ENEMY_DESTROYED',
    ENEMY_HIT: 'ENEMY_HIT',
    PLAYER_SPAWN: 'PLAYER_SPAWN',
    PLAYER_DESTROYED: 'PLAYER_DESTROYED',
    GAME_OVER: 'GAME_OVER',
    SHIP_HIT: 'SHIP_HIT',
    SHIP_SHOOT: 'SHIP_SHOOT',
    START_GAME: 'start-game',
    RESTART_GAME: 'restart-game',
    CONTINUE_GAME: 'continue-game',
    CLEANUP_GAME: 'cleanup-game',
    WEAPON_POWER_CHANGED: 'WEAPON_POWER_CHANGED',
    WEAPON_CHANGED: 'WEAPON_CHANGED',
    PLAYER_BOMB_ACTIVATED: 'player-bomb-activated',
    PLAYER_BOMB_DAMAGE_TICK: 'player-bomb-damage-tick',
    BOMB_COUNT_CHANGED: 'bomb-count-changed',
    POWER_CHANGED: 'power-changed',
    SETTINGS_CHANGED: 'SETTINGS_CHANGED',

    ADD_POWER: 'add-power',
    ADD_SCORE: 'add-score',
    ADD_BOMB: 'add-bomb',
    ADD_LIFE: 'add-life',
  
    START_SPAWNER: 'start-spawner',
    STOP_ALL_SPAWNERS: 'stop-all-spawners',
    RESET_ALL_SPAWNERS: 'reset-all-spawners',
    SPAWN_BOSS: 'spawn-boss',
    LEVEL_COMPLETE: 'level-complete',
    GAME_COMPLETE: 'game-complete',
    PLAYER_READY: 'player-ready',
    PAUSE_GAME: 'pause-game',
    RESUME_GAME: 'resume-game',
    ADD_BONUS_SCORE: 'add-bonus-score',
    
    BOSS_DEFEATED: 'boss-defeated',
    BOSS_SPAWNED: 'BOSS_SPAWNED',
    BOSS_INIT: 'BOSS_INIT',
    BOSS_PHASE_CHANGE: 'BOSS_PHASE_CHANGE',
    BOSS_HEALTH_CHANGE: 'BOSS_HEALTH_CHANGE',
} as const);
  
export type CustomEvents = typeof CUSTOM_EVENTS[keyof typeof CUSTOM_EVENTS];